import { kakebo2 } from "../assets";
import styles, { layout } from "../style";
import { GeneralListModel } from "../types";
import Button from "./Button";
import { motion } from "framer-motion";

type Props = {
  title?: string;
  content?: string;
  subContent?: string;
  showButton: boolean;
  image?: string;
  buttonText?: string;
  onclick?: () => void;
  plans?: GeneralListModel[];
  planName?: string;
  showMoreInfo?: boolean;
};

const AboutUs = (props: Props) => {
  const {
    title,
    content,
    showButton,
    subContent,
    image,
    buttonText,
    onclick,
    showMoreInfo = false,
  } = props;
  return (
    <motion.section
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{
        delay: 0.5,
        when: "beforeChildren",
      }}
      id="product"
      className={`${layout.section}  `}
    >
      <motion.div
        initial={{ x: "-100vw" }}
        animate={{ x: 0 }}
        transition={{ type: "spring", stiffness: 40 }}
        className={`${layout.sectionImg}`}
      >
        <div>
          <img
            src={image ? image : kakebo2}
            alt={title}
            className="h-full object-contain  "
          />
          {showMoreInfo && (
            <div className="hidden sm:block">
              <h1 className={` ${styles.heading3} mt-4  text-sm`}>
                Overview of Credit Unions
              </h1>

              <p
                className={`font-poppins md:p-0 text-justify   md:mt-0  leading-8`}
              >
                A credit union is a member-owned financial cooperative that
                provides a range of financial services to its members. Unlike
                traditional banks, which are typically for-profit institutions
                owned by shareholders, credit unions aim to be financially
                sustainable while operating as not-for-profit organizations.
                Profits generated by credit unions are reinvested into the
                organization to benefit its members, such as through low loan
                interest rates, higher interest rate on savings, or expanded
                services. Members of credit unions are both owners and
                customers, giving them a direct say in the management and
                operations of the institution.
              </p>

              <h1 className={` ${styles.heading3} mt-4  text-sm`}>
                Historical Context in Sierra Leone
              </h1>

              <p
                className={`font-poppins md:p-0 text-justify   md:mt-0  leading-8`}
              >
                The credit union movement in Sierra Leone traces its roots to
                the cooperative movement that began in the early to mid-20th
                century. Credit unions, also known as savings and credit
                cooperatives (SACCOs), emerged as part of this tradition. The
                regulation and supervision of credit unions fall under the
                Ministry of Trade and Industry through the Department of
                Cooperatives. The Cooperative Societies Act of 1977 provides the
                legal framework for the establishment and operation of credit
                unions in the country.
              </p>
            </div>
          )}
        </div>
      </motion.div>

      <motion.div
        initial={{ x: "100vw" }}
        animate={{ x: 0 }}
        transition={{ type: "spring", stiffness: 140 }}
        className={`${layout.sectionInfo}  pl-0 md:pl-10 `}
      >
        <div className="flex mt-10 md:mt-0 bg-redprimary w-14 h-[2px] mb-5  " />
        {title && <h1 className={` ${styles.heading2} `}>{title}</h1>}
        {content && (
          <p
            className={`font-poppins md:p-0 text-justify  mt-5 md:mt-0 lg:mt-5 leading-8`}
          >
            {content}
          </p>
        )}
        {subContent && (
          <p
            className={`font-poppins md:p-0 text-justify  mt-5 md:mt-0 lg:mt-5 leading-8`}
          >
            {subContent}
          </p>
        )}

        {showMoreInfo && (
          <div className=" sm:hidden">
            <h1 className={` ${styles.heading3} mt-4  text-sm`}>
              Overview of Credit Unions
            </h1>

            <p
              className={`font-poppins md:p-0 text-justify   md:mt-0  leading-8`}
            >
              A credit union is a member-owned financial cooperative that
              provides a range of financial services to its members. Unlike
              traditional banks, which are typically for-profit institutions
              owned by shareholders, credit unions aim to be financially
              sustainable while operating as not-for-profit organizations.
              Profits generated by credit unions are reinvested into the
              organization to benefit its members, such as through low loan
              interest rates, higher interest rate savings, or expanded
              services. Members of credit unions are both owners and customers,
              giving them a direct say in the management and operations of the
              institution.
            </p>

            <h1 className={` ${styles.heading3} mt-4  text-sm`}>
              Historical Context in Sierra Leone
            </h1>

            <p
              className={`font-poppins md:p-0 text-justify   md:mt-0  leading-8`}
            >
              The credit union movement in Sierra Leone traces its roots to the
              cooperative movement that began in the early to mid-20th century.
              Credit unions, also known as savings and credit cooperatives
              (SACCOs), emerged as part of this tradition. The regulation and
              supervision of credit unions fall under the Ministry of Trade and
              Industry through the Department of Cooperatives. The Cooperative
              Societies Act of 1977 provides the legal framework for the
              establishment and operation of credit unions in the country.
            </p>
          </div>
        )}

        {showMoreInfo && (
          <div className="">
            <h1 className={` ${styles.heading3} mt-4  text-sm`}>
              Recent Developments and Impact
            </h1>

            <p
              className={`font-poppins md:p-0 text-justify   md:mt-0  leading-8`}
            >
              Since 2020, SEND Sierra Leone has established 6 credit unions,
              providing additional financial services to individual members and
              Village Savings and Loans Association (VSLAs). This initiative has
              empowered thousands of women, making them financially literate,
              self reliant, and vocal in their communities. These credit unions
              have significantly increased income-earning opportunities and
              access to affordable loans, addressing social challenges such as
              gender inequality an decision-making in households and
              communities. As of June 2026, the 6 credit unions supported by
              SEND/SL and its partners, has over 5,000 individual memebers and
              over 1,000 VSLA groups, representing more than 30,000 members.
              These credit unions in Kenema, Kono, Bonthe and Falaba Districts
              have total assets valued at SLE 39,680,000 (approximately 1.6
              million USD).
            </p>
          </div>
        )}

        {showButton && (
          <Button
            onclick={() => {
              if (onclick) onclick();
            }}
            styles={
              "text-primary bg-redprimary lg:max-w-1/2 p-2 mt-4 md:mt-5 mb-4 md:mt-0  lg:text-[16px] "
            }
            text={buttonText ? buttonText : "Explore More"}
          />
        )}
      </motion.div>
    </motion.section>
  );
};

export default AboutUs;
